
services:
  jupyter-pyspark:
    image: quay.io/jupyter/pyspark-notebook:latest
    container_name: jupyter-pysparkk
    ports:
      # Spark UI
      - "4040:4040"
      # Jupyter notebook
      - "8888:8888"
    volumes:
      # Mount entire work directory
      - ./:/home/jovyan/work
      # Mount requirements.txt
      - ./requirements.txt:/home/jovyan/requirements.txt
    env_file:
      - ./.env
    command: >
      bash -c "pip install -r /home/jovyan/requirements.txt &&
      start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN}"

  db:
    container_name: postgres_labb
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_lab_pgadminn
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: