# Docker Compose file for setting up a Jupyter Notebook with PySpark, PostgreSQL, pgAdmin, Kafka, and Zookeeper
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes #set it to "no" for production
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper
    restart: unless-stopped

  jupyter-pyspark:
    image: quay.io/jupyter/pyspark-notebook:latest
    container_name: jupyter-pysparkk
    ports:
      - "4040:4040"    # Spark UI
      - "8888:8888"    # Jupyter
    volumes:
      - ./:/home/jovyan/work
      - ./drivers/postgresql-42.5.1.jar:/usr/local/spark/jars/postgresql-42.5.1.jar
    env_file:
      - .env           # loads JUPYTER_TOKEN, SPARK_OPTS, POSTGRES_*, PGADMIN_*
    depends_on:
      - db
    command: >
      bash -c "start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN}"

  db:
    container_name: postgres_labb
    image: postgres:latest
    env_file:
      - .env           # loads POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_lab_pgadminn
    env_file:
      - .env           # loads PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  kafka_data:
  zookeeper_data:
