FROM python:3.11-slim

# Set environment variable for Kaggle config
ENV KAGGLE_CONFIG_DIR=/root/.kaggle

# Set working directory inside the container
WORKDIR /app/data_extractor


# Install required Python packages
RUN pip install --no-cache-dir \
    kaggle \
    pandas \
    sqlalchemy \
    mysql-connector-python \
    python-dotenv



# Default command to run the script
CMD ["python", "data_extractor.py"]
